[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers]
  [certificatesResolvers.le.acme]
    email = "your-email@example.com"
    storage = "acme.json"
    [certificatesResolvers.le.acme.httpChallenge]
      entryPoint = "web"